services:
  db:
    image: postgres:17
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=plantTracker"
    volumes:
      - "./data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  api:
    build: ./api
    environment:
      - "DB_CONNECTION_STRING=postgresql://admin:admin@db:5432/plantTracker?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
  client:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - "API_BASE_URL=http://api:8080"
    depends_on:
      api:
        condition: service_started
